package com.uhg0.ar_flutter_plugin_2.visibilitygrid

import com.uhg0.ar_flutter_plugin_2.sceneview.RendererPressureSnapshot
import com.uhg0.ar_flutter_plugin_2.sceneview.RendererPageFramePressureSnapshot

/**
 * Non-observation owners sampled at the same debug boundary as the V2
 * observation runtime. Every value is scalar so a pressure campaign cannot
 * accidentally retain canonical rows, images, or renderer payloads. Worker,
 * capture and root-isolate metrics are unobserved zero placeholders in a native
 * snapshot, not proof that Dart owns no resources. The Dart owner boundary must
 * replace those fields before treating this as a combined certification receipt.
 */
internal data class VisibilityPressureOwnerScalars(
    val geometryRevision: Long = 0,
    val lineageRevision: Long = 0,
    val coverageRevision: Long = 0,
    val styleRevision: Long = 0,
    val canonicalSurfaceHighWater: Long = 0,
    val associationHighWater: Long = 0,
    val canonicalOwnedBytes: Long = 0,
    val rendererOwnedBytes: Long = 0,
    val maxUploadBytesPerFrame: Long = 0,
    val selectionChurnPermille: Long = 0,
    val workerMaxPendingTransactions: Long = 0,
    val workerCoalescedPresentations: Long = 0,
    val rootIsolateSurfaceBytes: Long = 0,
    val rootIsolateImageBytes: Long = 0,
    val captureMaxRunning: Long = 0,
    val captureMaxFundedWaiting: Long = 0,
    val manualWonWaitingSlot: Boolean = false,
    val buffersAcquired: Long = 0,
    val buffersReleased: Long = 0,
    val callbacksAcquired: Long = 0,
    val callbacksReleased: Long = 0,
    val pagesAcquired: Long = 0,
    val pagesReleased: Long = 0,
    val workerPortsAcquired: Long = 0,
    val workerPortsReleased: Long = 0,
    val rendererResourcesAcquired: Long = 0,
    val rendererResourcesReleased: Long = 0,
    val terminalGuidanceStatus: String = "unavailable",
) {
    init {
        require(nonNegativeValues().all { it >= 0 })
        require(terminalGuidanceStatus.isNotBlank() && terminalGuidanceStatus.length <= 64)
    }

    companion object {
        /** Only native owners are sampled here; Dart supplies its own fields. */
        fun fromNativeOwners(
            canonical: CanonicalVisibilityPressureSnapshot,
            renderer: RendererPressureSnapshot,
            pages: RendererPageFramePressureSnapshot,
        ) = VisibilityPressureOwnerScalars(
            geometryRevision = canonical.geometryRevision,
            lineageRevision = canonical.lineageRevision,
            coverageRevision = canonical.coverageRevision,
            styleRevision = canonical.styleRevision,
            canonicalSurfaceHighWater = canonical.canonicalSurfaceHighWater,
            associationHighWater = canonical.associationHighWater,
            canonicalOwnedBytes = canonical.canonicalOwnedBytes,
            rendererOwnedBytes = renderer.rendererOwnedBytes,
            maxUploadBytesPerFrame = renderer.maxUploadBytesPerFrame,
            selectionChurnPermille = renderer.selectionChurnPermille,
            buffersAcquired = renderer.buffersAcquired,
            buffersReleased = renderer.buffersReleased,
            callbacksAcquired = renderer.callbacksAcquired,
            callbacksReleased = renderer.callbacksReleased,
            pagesAcquired = pages.pagesAcquired,
            pagesReleased = pages.pagesReleased,
            rendererResourcesAcquired = renderer.rendererResourcesAcquired,
            rendererResourcesReleased = renderer.rendererResourcesReleased,
            terminalGuidanceStatus = canonical.terminalGuidanceStatus,
        )
    }

    private fun nonNegativeValues(): List<Long> = listOf(
        geometryRevision,
        lineageRevision,
        coverageRevision,
        styleRevision,
        canonicalSurfaceHighWater,
        associationHighWater,
        canonicalOwnedBytes,
        rendererOwnedBytes,
        maxUploadBytesPerFrame,
        selectionChurnPermille,
        workerMaxPendingTransactions,
        workerCoalescedPresentations,
        rootIsolateSurfaceBytes,
        rootIsolateImageBytes,
        captureMaxRunning,
        captureMaxFundedWaiting,
        buffersAcquired,
        buffersReleased,
        callbacksAcquired,
        callbacksReleased,
        pagesAcquired,
        pagesReleased,
        workerPortsAcquired,
        workerPortsReleased,
        rendererResourcesAcquired,
        rendererResourcesReleased,
    )
}

/** Fixed-schema, scalar-only evidence emitted by a pressure campaign. */
internal data class VisibilityPressureReceipt(
    val groupGeneration: Long,
    val bindingGeneration: Long,
    val featureOffered: Long,
    val featureAdmitted: Long,
    val featureCoalesced: Long,
    val featureDropped: Long,
    val featureMaxSamples: Long,
    val featureMaxHz: Long,
    val depthOffered: Long,
    val depthAdmitted: Long,
    val depthCoalesced: Long,
    val depthDropped: Long,
    val depthMaxSamples: Long,
    val depthMaxHz: Long,
    val callbackCopyP95Micros: Long,
    val geometryRevision: Long,
    val lineageRevision: Long,
    val coverageRevision: Long,
    val styleRevision: Long,
    val canonicalSurfaceHighWater: Long,
    val associationHighWater: Long,
    val canonicalOwnedBytes: Long,
    val rendererOwnedBytes: Long,
    val maxUploadBytesPerFrame: Long,
    val selectionChurnPermille: Long,
    val workerMaxPendingTransactions: Long,
    val workerCoalescedPresentations: Long,
    val rootIsolateSurfaceBytes: Long,
    val rootIsolateImageBytes: Long,
    val captureMaxRunning: Long,
    val captureMaxFundedWaiting: Long,
    val manualWonWaitingSlot: Boolean,
    val featureLatestSlots: Long,
    val depthLatestSlots: Long,
    val catchUpBursts: Long,
    val imagesAcquired: Long,
    val imagesReleased: Long,
    val buffersAcquired: Long,
    val buffersReleased: Long,
    val callbacksAcquired: Long,
    val callbacksReleased: Long,
    val pagesAcquired: Long,
    val pagesReleased: Long,
    val workerPortsAcquired: Long,
    val workerPortsReleased: Long,
    val rendererResourcesAcquired: Long,
    val rendererResourcesReleased: Long,
    val terminalDepthMode: String,
    val terminalGuidanceStatus: String,
) {
    init {
        require(toWireMap().values.filterIsInstance<Number>().all { it.toLong() >= 0 })
        require(featureAdmitted + featureCoalesced + featureDropped <= featureOffered)
        require(depthAdmitted + depthCoalesced + depthDropped <= depthOffered)
        require(featureLatestSlots <= 1 && depthLatestSlots <= 1)
        require(terminalDepthMode.isNotBlank() && terminalDepthMode.length <= 64)
        require(terminalGuidanceStatus.isNotBlank() && terminalGuidanceStatus.length <= 64)
    }

    fun toWireMap(): Map<String, Any> = linkedMapOf(
        "groupGeneration" to groupGeneration,
        "bindingGeneration" to bindingGeneration,
        "featureOffered" to featureOffered,
        "featureAdmitted" to featureAdmitted,
        "featureCoalesced" to featureCoalesced,
        "featureDropped" to featureDropped,
        "featureMaxSamples" to featureMaxSamples,
        "featureMaxHz" to featureMaxHz,
        "depthOffered" to depthOffered,
        "depthAdmitted" to depthAdmitted,
        "depthCoalesced" to depthCoalesced,
        "depthDropped" to depthDropped,
        "depthMaxSamples" to depthMaxSamples,
        "depthMaxHz" to depthMaxHz,
        "callbackCopyP95Micros" to callbackCopyP95Micros,
        "geometryRevision" to geometryRevision,
        "lineageRevision" to lineageRevision,
        "coverageRevision" to coverageRevision,
        "styleRevision" to styleRevision,
        "canonicalSurfaceHighWater" to canonicalSurfaceHighWater,
        "associationHighWater" to associationHighWater,
        "canonicalOwnedBytes" to canonicalOwnedBytes,
        "rendererOwnedBytes" to rendererOwnedBytes,
        "maxUploadBytesPerFrame" to maxUploadBytesPerFrame,
        "selectionChurnPermille" to selectionChurnPermille,
        "workerMaxPendingTransactions" to workerMaxPendingTransactions,
        "workerCoalescedPresentations" to workerCoalescedPresentations,
        "rootIsolateSurfaceBytes" to rootIsolateSurfaceBytes,
        "rootIsolateImageBytes" to rootIsolateImageBytes,
        "captureMaxRunning" to captureMaxRunning,
        "captureMaxFundedWaiting" to captureMaxFundedWaiting,
        "manualWonWaitingSlot" to manualWonWaitingSlot,
        "featureLatestSlots" to featureLatestSlots,
        "depthLatestSlots" to depthLatestSlots,
        "catchUpBursts" to catchUpBursts,
        "imagesAcquired" to imagesAcquired,
        "imagesReleased" to imagesReleased,
        "buffersAcquired" to buffersAcquired,
        "buffersReleased" to buffersReleased,
        "callbacksAcquired" to callbacksAcquired,
        "callbacksReleased" to callbacksReleased,
        "pagesAcquired" to pagesAcquired,
        "pagesReleased" to pagesReleased,
        "workerPortsAcquired" to workerPortsAcquired,
        "workerPortsReleased" to workerPortsReleased,
        "rendererResourcesAcquired" to rendererResourcesAcquired,
        "rendererResourcesReleased" to rendererResourcesReleased,
        "terminalDepthMode" to terminalDepthMode,
        "terminalGuidanceStatus" to terminalGuidanceStatus,
    )

    companion object {
        fun capture(
            observation: VisibilityObservationHealth,
            owners: VisibilityPressureOwnerScalars = VisibilityPressureOwnerScalars(),
        ): VisibilityPressureReceipt = VisibilityPressureReceipt(
            groupGeneration = observation.admittedGroupGeneration,
            bindingGeneration = observation.admittedBindingGeneration,
            featureOffered = observation.offeredFeatureObservations,
            featureAdmitted = observation.admittedFeatureObservations,
            featureCoalesced = observation.replacedFeatureObservations,
            featureDropped = observation.droppedFeatureObservations,
            featureMaxSamples = observation.maximumFeatureSamples.toLong(),
            featureMaxHz = observation.featureMaximumHz,
            depthOffered = observation.offeredDepthObservations,
            depthAdmitted = observation.admittedDepthObservations,
            depthCoalesced = observation.replacedDepthObservations,
            depthDropped = observation.droppedDepthObservations,
            depthMaxSamples = observation.maximumDepthSamples.toLong(),
            depthMaxHz = observation.depthMaximumHz,
            callbackCopyP95Micros = observation.callbackCopyP95Ns / 1_000L,
            geometryRevision = owners.geometryRevision,
            lineageRevision = owners.lineageRevision,
            coverageRevision = owners.coverageRevision,
            styleRevision = owners.styleRevision,
            canonicalSurfaceHighWater = owners.canonicalSurfaceHighWater,
            associationHighWater = owners.associationHighWater,
            canonicalOwnedBytes = owners.canonicalOwnedBytes,
            rendererOwnedBytes = owners.rendererOwnedBytes,
            maxUploadBytesPerFrame = owners.maxUploadBytesPerFrame,
            selectionChurnPermille = owners.selectionChurnPermille,
            workerMaxPendingTransactions = owners.workerMaxPendingTransactions,
            workerCoalescedPresentations = owners.workerCoalescedPresentations,
            rootIsolateSurfaceBytes = owners.rootIsolateSurfaceBytes,
            rootIsolateImageBytes = owners.rootIsolateImageBytes,
            captureMaxRunning = owners.captureMaxRunning,
            captureMaxFundedWaiting = owners.captureMaxFundedWaiting,
            manualWonWaitingSlot = owners.manualWonWaitingSlot,
            featureLatestSlots = 1,
            depthLatestSlots = 1,
            catchUpBursts = 0,
            imagesAcquired = observation.acquiredProducerResources,
            imagesReleased = observation.closedProducerResources,
            buffersAcquired = owners.buffersAcquired,
            buffersReleased = owners.buffersReleased,
            callbacksAcquired = owners.callbacksAcquired,
            callbacksReleased = owners.callbacksReleased,
            pagesAcquired = owners.pagesAcquired,
            pagesReleased = owners.pagesReleased,
            workerPortsAcquired = owners.workerPortsAcquired,
            workerPortsReleased = owners.workerPortsReleased,
            rendererResourcesAcquired = owners.rendererResourcesAcquired,
            rendererResourcesReleased = owners.rendererResourcesReleased,
            terminalDepthMode = observation.depthCapability.wireName,
            terminalGuidanceStatus = owners.terminalGuidanceStatus,
        )
    }
}
